addons:
  apt:
    sources:
    - libxml2-utils
    - python-matplotlib
language: python
python:
  - "2.7"
cache: pip
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - pytest
