sudo: required
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libxml2-dev libxml2-utils
  - sudo apt-get build-dep -y python-matplotlib
language: python
python:
  - "2.7"
cache: pip
install:
  - pip install pytest
  - pip install -r requirements.txt
script:
  - pytest
